#!/bin/bash
echo "Starting StationMaster"
path=`dirname $0`
cd $path
./stationmaster.py lion-mills

#if there's no keyboard plugged in, shutdown
#otherwise let the system go to the prompt
keyboards=`wc -l /proc/bus/input/devices | cut -d' ' -f1`
if [ $keyboards == "0" ]; then
    echo "Auto halting system"
    halt
else
    echo "keyboard present, exiting";
fi

