#!/bin/bash
echo "Starting YardMaster"
path=`dirname $0`
cd $path
./yardmaster.py lion-mills

if [ -f ./autohalt ]; then
    echo "Auto halting system"
    halt;
else
    echo "No autohalt, exiting";
fi

